### ISSUE TITLE
Required property 'url' is missing

### ISSUE THREAD

**Issue by chuckurbis** [getlarge/nx-heroku#20]
Hello, 

I've been banging my head against the wall trying to sort this out. I've followed the instructions as closely as I could. I'm trying to deploy a node application to heroku. I've even tried creating bare bones node projects within my NX repo, but so far no luck. I always end up with this error message when I run the build target:

`Required property 'url' is missing
`

Any direction would be greatly appreciated.

**Comment by getlarge** [comment]
Hey, 

Sorry for you!
Could you show me how you configured your Nx project(s)?
Even better if you have a repository that reproduces the issue.

**Comment by chuckurbis** [comment]
Thanks for the fast reply. I tried two different projects. One was my ongoing express based one. The config I used was: 

`
    "deploy": {
      "executor": "@getlarge/nx-heroku:deploy",
      "options": {
        
        "appNamePrefix": "server-test",
        "buildPacks": [
          "heroku/nodejs",
          "heroku-community/multi-procfile"
        ],
        "variables": { },
        "useForce": true,
        "debug": true
      }
    },
  
  
  `

I also tried it with a generated regular node app, and got the same issue. For now I ended up going a different route so I could get it to deploy but I will try to do it again some time this week. I'd really prefer to use this lib to get it running. I can't share my work repo, but I can perhaps make a stripped down version to further test.

**Comment by getlarge** [comment]
Thanks for sharing the options that confirms what i suspected. Until now I always declared the `webhook` option with a `url` property. Now i suppose that when it is missing it leads to the error you encountered. I’ll try to push and release a fix ASAP.

**Comment by getlarge** [comment]
related to https://github.com/nrwl/nx/issues/23153

**Comment by getlarge** [comment]
@chuckurbis version 0.4.3 of `@getlarge/nx-heroku` is released.

**Comment by chuckurbis** [comment]
Awesome @getlarge I'll check that out in the next few days. Thanks for the quick fix!
